[mgr]
show_hidden = true

[opener]
edit = [
    { run = 'nvim %s', desc = "Editor", block = true },
]
pdf = [
    { run = 'firefox %s', desc = "Firefox PDF Viewer", orphan = true },
]

[[open.rules]]
url = "*.md"
use = "edit"

[[open.rules]]
url = "*.txt"
use = "edit"

[[open.rules]]
mime = "text/*"
use = "edit"

[[open.rules]]
url = "*.pdf"
use = "pdf"
